name: Build Tweak
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        run: |
          rm -rf /home/runner/theos
          git clone --recursive https://github.com/theos/theos.git /home/runner/theos
          git clone https://github.com/theos/sdks.git /home/runner/theos/sdks
          git clone https://github.com/theos/toolchain-linux.git /home/runner/theos/toolchain
      - name: Build
        run: |
          export THEOS=/home/runner/theos
          make
